// This file is auto-generated by `payload generate:importmap`
// It maps custom admin component paths to their actual imports.
// For a standard setup with no custom admin components, this is empty.
export const importMap = {}
